apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpapp-deployment
  namespace: webapp-namespace
  labels:
    app: phpapp
    environment: test
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  selector:
    matchLabels:
      app: phpapp
      environment: test
  template:
    metadata:
      labels:
        app: phpapp
        environment: test
    spec:
      containers:
      - name: app-container
        image: praveenedulakanti/phpapp:3.0
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        resources: 
          limits:
            memory: 200Mi
            cpu: 200m
          requests:
            memory: 200Mi
            cpu: 200m
        env:
          - name: "PORT"
            value: "80"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
