apiVersion: v1
kind: Service
metadata:
  name: phpapp
  namespace: webapp-namespace
  labels:
    app: phpapp
    environment: test
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
      app: phpapp
      environment: test
